# Generated by Django 2.2.3 on 2019-07-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcbuild',
            name='memory',
            field=models.ManyToManyField(blank=True, to='parts.Memory'),
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='storage',
            field=models.ManyToManyField(blank=True, to='parts.Storage'),
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='videocard',
            field=models.ManyToManyField(blank=True, to='parts.Videocard'),
        ),
    ]
