# Generated by Django 2.2.3 on 2019-07-28 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='memory',
            field=models.ManyToManyField(blank=True, to='parts.Memory'),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='mobo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.Mobo'),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='storage',
            field=models.ManyToManyField(blank=True, to='parts.Storage'),
        ),
        migrations.AddField(
            model_name='pcbuild',
            name='videocard',
            field=models.ManyToManyField(blank=True, to='parts.Videocard'),
        ),
    ]
