# Generated by Django 2.2.3 on 2019-07-28 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=16)),
                ('model_name', models.CharField(max_length=16)),
                ('part_number', models.CharField(max_length=18)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Part')),
                ('series', models.CharField(max_length=16)),
                ('family', models.CharField(max_length=16)),
                ('cores', models.IntegerField()),
                ('threads', models.IntegerField()),
                ('base_clock', models.FloatField()),
                ('boost_clock', models.FloatField()),
            ],
            options={
                'ordering': ['series'],
            },
            bases=('parts.part',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Part')),
                ('speed', models.CharField(max_length=16)),
                ('frequency', models.IntegerField()),
                ('memory_type', models.CharField(max_length=16)),
                ('isdual', models.BooleanField(default=False)),
                ('ram', models.IntegerField(verbose_name='Memory')),
                ('cas_latency', models.IntegerField()),
                ('isecc', models.BooleanField(verbose_name='Is ECC')),
            ],
            options={
                'ordering': ['model_name'],
            },
            bases=('parts.part',),
        ),
        migrations.CreateModel(
            name='Mobo',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Part')),
                ('socket', models.CharField(choices=[('AM3+', 'AM3+'), ('AM4', 'AM4'), ('TR4', 'TR4'), ('LGA1151', 'LGA1151'), ('LGA2011-3', 'LGA2011-3')], max_length=16)),
                ('chipset', models.CharField(choices=[('B450', 'AMD B450'), ('B350', 'AMD B350'), ('X470', 'AMD X470'), ('X370', 'AMD X370'), ('X399', 'AMD X399'), ('X570', 'AMD X570'), ('B360', 'Intel B360'), ('Z390', 'Intel Z390'), ('Z170', 'Intel Z170'), ('Z270', 'Intel Z270'), ('Z370', 'Intel Z370')], max_length=16)),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('EATX', 'EATX'), ('XL ATX', 'XL ATX'), ('mATX', 'micro ATX'), ('mITX', 'mini ITX')], max_length=8)),
                ('ram_slots', models.IntegerField()),
                ('max_ram', models.IntegerField()),
                ('sata', models.IntegerField()),
                ('m2', models.IntegerField()),
                ('pcie', models.IntegerField()),
            ],
            options={
                'ordering': ['chipset'],
            },
            bases=('parts.part',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Part')),
                ('capacity', models.IntegerField()),
                ('cache', models.IntegerField()),
                ('interface', models.CharField(choices=[('SATA', 'Serial ATA'), ('FC', 'Fiber Channel'), ('SAS', 'Serial attached SCSI'), ('PCIe', 'Peripheral Component Interconnect Express'), ('USB', 'USB')], max_length=16)),
            ],
            bases=('parts.part',),
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Part')),
                ('chipset', models.CharField(max_length=64)),
                ('vram', models.IntegerField(verbose_name='Memory')),
                ('base_clock', models.IntegerField()),
                ('boost_clock', models.IntegerField()),
            ],
            options={
                'ordering': ['model_name'],
            },
            bases=('parts.part',),
        ),
    ]
